### ISSUE TITLE
Not compatible with current version of Visual Studio Code (version 1.76.0)

### ISSUE THREAD

**Issue by pogmothon** [ThomasLatham/markdown-pdf-plus#1]
Attempting to install, but received a message saying that it can't be installed because it is not compatible with the current version of Visual Studio Code.  The version I am on is 1.76.0.

**Comment by ThomasLatham** [comment]
Thanks @pogmothon for bringing this to my attention! I'll look into it and get back to you as soon as I can

**Comment by ThomasLatham** [comment]
@pogmothon after having done some research, the issue is that I have by default made the extension only compatible with 
VS Code versions greater than or equal to 1.78. This is set in the extension manifest under the `engines` property, as you can [read about here in the VS Code Extension API documentation](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#visual-studio-code-compatibility). You can also see the relevant section from `package.json` below:

https://github.com/ThomasLatham/markdown-pdf-plus/blob/4359d170d74a8d71661c71473ab75c8e1bd3855e/package.json#L1-L7

I also downloaded VS Code version 1.75.0 to see if I could use Markdown PDF Plus, and I was met with the following:
![image](https://github.com/ThomasLatham/markdown-pdf-plus/assets/32628434/d87ede3c-71ec-4e64-b0b7-bb02da2c7b93)

So I would recommend that to remedy this issue, you should upgrade your VS Code installation to a version greater than or equal to 1.78.0.

**Comment by pogmothon** [comment]
Thank you very much!

**Comment by ThomasLatham** [comment]
You're welcome! Thank you for checking out the extension and taking the time to contribute this issue!
